In [ ]:
# Write a Python program that solves a system of inequalities with a 4 x 4 square matrix A where Ax=b.

In [30]:
# Import the dependencies
import numpy as np

In [31]:
arr_a = np.array([[3,-9,2,1], [2,4,3,6], [5,3,1,2], [6,2,1,2]])

In [32]:
print(arr_a)

[[ 3 -9  2  1]
 [ 2  4  3  6]
 [ 5  3  1  2]
 [ 6  2  1  2]]


In [33]:
arr_b = np.array([-25,2,5,3])

In [34]:
print(arr_b)

[-25   2   5   3]


In [35]:
# Soling the 4X4 matrix
z = np.linalg.solve(arr_a,arr_b)

In [36]:
print(z)

[ 0.16666667  2.16666667 -3.22222222  0.44444444]
